# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import calculator_pb2 as calculator__pb2


class CalculatorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.add = channel.unary_unary(
                '/calculator.Calculator/add',
                request_serializer=calculator__pb2.TwoFloats.SerializeToString,
                response_deserializer=calculator__pb2.Float.FromString,
                )
        self.sub = channel.unary_unary(
                '/calculator.Calculator/sub',
                request_serializer=calculator__pb2.TwoFloats.SerializeToString,
                response_deserializer=calculator__pb2.Float.FromString,
                )
        self.rand = channel.unary_stream(
                '/calculator.Calculator/rand',
                request_serializer=calculator__pb2.TwoFloats.SerializeToString,
                response_deserializer=calculator__pb2.Integer.FromString,
                )
        self.info = channel.unary_unary(
                '/calculator.Calculator/info',
                request_serializer=calculator__pb2.Empty.SerializeToString,
                response_deserializer=calculator__pb2.CalcInfo.FromString,
                )


class CalculatorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def add(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def sub(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def rand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def info(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CalculatorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'add': grpc.unary_unary_rpc_method_handler(
                    servicer.add,
                    request_deserializer=calculator__pb2.TwoFloats.FromString,
                    response_serializer=calculator__pb2.Float.SerializeToString,
            ),
            'sub': grpc.unary_unary_rpc_method_handler(
                    servicer.sub,
                    request_deserializer=calculator__pb2.TwoFloats.FromString,
                    response_serializer=calculator__pb2.Float.SerializeToString,
            ),
            'rand': grpc.unary_stream_rpc_method_handler(
                    servicer.rand,
                    request_deserializer=calculator__pb2.TwoFloats.FromString,
                    response_serializer=calculator__pb2.Integer.SerializeToString,
            ),
            'info': grpc.unary_unary_rpc_method_handler(
                    servicer.info,
                    request_deserializer=calculator__pb2.Empty.FromString,
                    response_serializer=calculator__pb2.CalcInfo.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'calculator.Calculator', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Calculator(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def add(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.Calculator/add',
            calculator__pb2.TwoFloats.SerializeToString,
            calculator__pb2.Float.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def sub(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.Calculator/sub',
            calculator__pb2.TwoFloats.SerializeToString,
            calculator__pb2.Float.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def rand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/calculator.Calculator/rand',
            calculator__pb2.TwoFloats.SerializeToString,
            calculator__pb2.Integer.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def info(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/calculator.Calculator/info',
            calculator__pb2.Empty.SerializeToString,
            calculator__pb2.CalcInfo.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
